name: screen_brightness
description: A flutter plugin to get and set screen brightness.
version: 0.2.0
homepage: https://github.com/DeMiA-KK/flutter_screen_brightness

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: jp.co.demia.screen_brightness
        pluginClass: ScreenBrightnessPlugin
      ios:
        pluginClass: ScreenBrightnessPlugin
